In [1]:
import tensorflow
from tensorflow.python.keras.datasets import mnist
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Dropout
from tensorflow.python.keras.optimizers import RMSprop

batch_size = 64
num_classes = 10
epochs = 20

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = tensorflow.keras.utils.to_categorical(y_train, num_classes)
y_test = tensorflow.keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

60000 train samples
10000 test samples
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
__

In [2]:
from sklearn.metrics import classification_report,confusion_matrix
import numpy as np
Y_pred = model.predict(x_test)
print(Y_pred)
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)

target_names = ['0', '1', '2','3','4','5','6','7','8','9']
#print(classification_report(np.argmax(x_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(y_test,axis=1), y_pred))

[[2.1514729e-20 3.1548277e-14 3.3627053e-11 ... 1.0000000e+00
  1.7242171e-15 3.6448200e-10]
 [9.0328639e-17 7.4847810e-13 1.0000000e+00 ... 7.2948968e-15
  9.0163142e-15 8.9232561e-20]
 [2.3126725e-26 1.0000000e+00 1.4996618e-14 ... 5.6602287e-13
  2.1484665e-13 2.6350042e-20]
 ...
 [8.9987282e-21 3.8312666e-14 3.3825271e-17 ... 3.6696980e-16
  2.2442011e-15 2.2330603e-12]
 [3.2385227e-23 5.6950843e-33 6.1163683e-26 ... 3.9004189e-30
  3.4732156e-19 1.0716406e-23]
 [6.4035331e-22 1.8903563e-21 3.7319396e-24 ... 3.6795365e-32
  8.5179248e-17 2.8663560e-26]]
[7 2 1 ... 4 5 6]
[[ 969    1    1    0    0    0    4    2    2    1]
 [   0 1125    4    0    0    1    2    1    2    0]
 [   1    1 1010    3    3    0    3    6    5    0]
 [   0    0    6  990    0    2    0    4    5    3]
 [   0    1    1    0  953    0    7    5    0   15]
 [   1    0    0    9    1  869    4    2    5    1]
 [   2    2    0    0    3    4  946    0    1    0]
 [   2    2    9    1    0    0    0 1009    3 

In [3]:
file_json = open("modelBEST_64.json", "r")
load_json = file_json.read()
file_json.close()
load = tensorflow.keras.models.model_from_json(load_json)
load.load_weights("modelBEST_64.h5")

Y_pred = load.predict(x_test)
print(Y_pred)
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)

target_names = ['0', '1', '2','3','4','5','6','7','8','9']
print(classification_report(np.argmax(y_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(y_test,axis=1), y_pred))


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[[3.8115390e-20 4.0378342e-18 4.5256481e-17 ... 1.0000000e+00
  1.1532992e-17 3.8470655e-12]
 [5.4871588e-17 2.1374796e-13 1.0000000e+00 ... 2.6993457e-19
  2.5161725e-19 7.6497311e-25]
 [1.7102484e-18 1.0000000e+00 9.2796983e-15 ... 4.4534946e-14
  3.2039330e-15 2.3283654e-20]
 ...
 [3.3660674e-30 3.9380516e-29 3.1682089e-25 ... 1.4112725e-19
  1.2545911e-24 2.7601063e-17]
 [2.2233741e-16 1.7616508e-27 3.4980437e-32 ... 3.5940560e-23
  6.5296623e-13 2.0454734e-23]
 [5.2430390e-17 1.9260818e-21 3.7774865e-24 ... 1.7933171e-25
  1.1984914e-17 2.1185154e-18]]
[7 2 1 ... 4 5 6]
             precision    recall  f1-score   support

          0       0.98      0.99      0.99       980
          1       0.99      1.00      0.99      1135
          2       0.99